### ISSUE TITLE
Curious cat question

### ISSUE THREAD

**Issue by angeldollface** [alexwlchan/books.alexwlchan.net#81]
Hi Alex! :wave: Great job with building your book-tracking website. I like the design and idea. However, I do have a question: What is the architecture of this project? What role does the :crab: play? I have a similar project [here](https://github.com/angeldollface/mandy). Mandy is a new static-site generator built solely by me in the last two weeks. The architecture is quite simple: Mandy fetches all the info from the Mandy project directory, stores this info in a structure and generates the static site's files from this info. In the same way, what is the architecture you used for your project? I'm just curious! :see_no_evil:

**Comment by alexwlchan** [comment]
Hi Mandy! Depends what you mean by "architecture" – my tool reads a bunch of Markdown source files from the `reviews` folder, one file per review, then renders those as HTML. I upload the HTML files to Netlify, which is what serves the site. It's a pretty vanilla static site generator pattern. I picked Rust just for practice, really.

Happy to answer more specific questions if you have them!

**Comment by angeldollface** [comment]
Hey, Alex! :see_no_evil: My name isn't Mandy, rather it is the name of the static-site generator I linked to earlier. About the architecture: That's very interesting! My static-site generator does the same actually and Netlify is one of the supported deployment services. Would you be interested in using Mandy (the SSG) for this project? I'd be thrilled and help you as best I can, obviously!

**Comment by alexwlchan** [comment]
> Hey, Alex! 🙈 My name isn't Mandy, rather it is the name of the static-site generator I linked to earlier. 

🤦‍♀️ So sorry, I should have paid more attention!

> Would you be interested in using Mandy (the SSG) for this project?

Thanks, but not right now. I already have a setup that works, and if I was to switch I'd probably look to replace my custom-built Rust tool with something I'm already familiar with (probably Jekyll tbh).

**Comment by angeldollface** [comment]
No, no don't worry!!! It's fine. 🙈 It was just a suggestion, should you ever decide to use Mandy, you are more than welcome. :heart_on_fire:
